# Generated by Django 3.2.25 on 2025-10-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialplan',
            name='season',
        ),
        migrations.AddField(
            model_name='trialplanculturetrialtype',
            name='season',
            field=models.CharField(choices=[('spring', 'Весна'), ('autumn', 'Осень'), ('summer', 'Лето'), ('winter', 'Зима')], default='spring', help_text='Сезон посадки/посева для данного типа испытания', max_length=20),
        ),
    ]
