# Generated by Django 3.2.25 on 2025-10-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0002_auto_20251016_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='decided_by',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='decision_date',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='decision_justification',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='decision_recommendations',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='laboratory_code',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='sort_records',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='trial_plan_source',
        ),
        migrations.RemoveField(
            model_name='trialresult',
            name='plot_1',
        ),
        migrations.RemoveField(
            model_name='trialresult',
            name='plot_2',
        ),
        migrations.RemoveField(
            model_name='trialresult',
            name='plot_3',
        ),
        migrations.RemoveField(
            model_name='trialresult',
            name='plot_4',
        ),
        migrations.AlterField(
            model_name='trial',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('active', 'Проводится'), ('completed_008', 'Уборка завершена'), ('lab_sample_sent', 'Образец в лаборатории'), ('lab_completed', 'Лабораторный анализ завершен'), ('completed', 'Завершено')], default='planned', max_length=20),
        ),
    ]
