# Generated by Django 3.2.25 on 2025-10-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0003_remove_unused_trial_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialplan',
            name='total_varieties',
        ),
        migrations.AddField(
            model_name='trialplan',
            name='total_participants',
            field=models.IntegerField(default=0, help_text='Общее количество участников в плане'),
        ),
    ]
