# Generated by Django 3.2.25 on 2025-10-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0004_rename_total_varieties_to_total_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialplanparticipant',
            name='seeds_provision',
            field=models.CharField(choices=[('provided', 'Предоставлены'), ('not_provided', 'Не предоставлены')], default='provided', help_text='Обеспеченность семенами', max_length=20),
        ),
    ]
