# Generated by Django 3.2.25 on 2025-10-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0005_change_seeds_provision_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='calculation_formula',
            field=models.TextField(blank=True, help_text='Формула расчета (если показатель авторасчетный)', null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='is_auto_calculated',
            field=models.BooleanField(default=False, help_text='Авторасчетный показатель (вычисляется автоматически на основе других данных)'),
        ),
    ]
