# Generated by Django 3.2.25 on 2025-10-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0006_auto_20251016_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='is_recommended',
            field=models.BooleanField(default=True, help_text='Рекомендуемый дополнительный показатель'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Обязательный показатель по методике государственного сортоиспытания'),
        ),
    ]
