# Generated by Django 3.2.25 on 2025-10-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0007_auto_20251016_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='validation_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Правила валидации: {"min_value": 0, "max_value": 100, "required": true, "precision": 2}'),
        ),
    ]
