# Generated by Django 3.2.25 on 2025-10-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0010_trial_participant_and_result_form008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='lsd_095',
            field=models.FloatField(blank=True, help_text="Наименьшая существенная разность (ц/га). ОБЯЗАТЕЛЬНО для автоматического расчета 'Группы по стат. обработке'! Вводится вручную на основе дисперсионного анализа.", null=True, verbose_name='НСР₀.₉₅'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='maturity_group_name',
            field=models.CharField(blank=True, help_text='Название группы спелости (Среднеранняя группа, D-03 и т.д.). КРИТИЧНО: форма 008 заполняется строго для одной группы!', max_length=100, null=True, verbose_name='Группа спелости'),
        ),
    ]
