# Generated by Django 3.2.25 on 2025-10-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0011_auto_20251017_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='growing_conditions',
            field=models.CharField(blank=True, choices=[('rainfed', 'Богара'), ('irrigated', 'Орошение'), ('drained', 'На осушенных почвах'), ('mixed', 'Смешанное')], help_text='Условия выращивания', max_length=20, null=True),
        ),
    ]
