# Generated by Django 3.2.25 on 2025-10-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0012_add_drained_soils_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='patents_culture_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID культуры в Patents Service', null=True),
        ),
    ]
