# Generated by Django 3.2.25 on 2025-10-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0013_add_patents_culture_id_to_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialparticipant',
            name='subgroup_code',
            field=models.CharField(blank=True, help_text='Код подгруппы внутри организационной группы (назначение, сила роста и т.д.)', max_length=20, null=True, verbose_name='Код подгруппы'),
        ),
    ]
