# Generated by Django 3.2.25 on 2025-10-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0015_remove_laboratory_code_from_trial_laboratory_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialparticipant',
            name='subgroup_code',
        ),
    ]
