# Generated by Django 3.2.25 on 2025-10-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0016_remove_trialparticipant_subgroup_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualdecisionitem',
            name='years_tested',
            field=models.IntegerField(default=0, help_text='Количество лет испытаний (1, 2 или 3)'),
        ),
    ]
