# Generated by Django 3.2.25 on 2025-10-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0017_alter_annualdecisionitem_years_tested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualdecisionitem',
            name='year_started',
            field=models.IntegerField(blank=True, help_text='Год начала испытаний (например: 2022)', null=True),
        ),
    ]
