# Generated by Django 3.2.25 on 2025-10-18 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0018_alter_annualdecisionitem_year_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationOblastStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('trial_plan_created', 'План создан'), ('trial_created', 'Испытание создано'), ('trial_in_progress', 'Испытание идет'), ('trial_completed', 'Испытание завершено'), ('decision_pending', 'Ожидает решения'), ('decision_made', 'Решение принято'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('continue', 'Продолжить')], default='planned', help_text='Статус заявки для конкретной области', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_decision_item', models.ForeignKey(blank=True, help_text='Связанное решение в годовой таблице', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_oblast_statuses', to='trials_app.annualdecisionitem')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oblast_statuses', to='trials_app.application')),
                ('oblast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_statuses', to='trials_app.oblast')),
                ('trial', models.ForeignKey(blank=True, help_text='Связанное испытание', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_oblast_statuses', to='trials_app.trial')),
                ('trial_plan', models.ForeignKey(blank=True, help_text='Связанный план испытаний', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_oblast_statuses', to='trials_app.trialplan')),
            ],
            options={
                'verbose_name': 'Статус заявки по области',
                'verbose_name_plural': 'Статусы заявок по областям',
                'ordering': ['application', 'oblast'],
                'unique_together': {('application', 'oblast')},
            },
        ),
    ]
