# Generated by Django 3.2.25 on 2025-10-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0019_create_application_oblast_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationoblaststatus',
            name='status',
            field=models.CharField(
                choices=[
                    ('planned', 'Запланировано'),
                    ('trial_plan_created', 'План создан'),
                    ('trial_created', 'Испытание создано'),
                    ('trial_in_progress', 'Испытание идет'),
                    ('trial_completed', 'Испытание завершено'),
                    ('decision_pending', 'Ожидает решения'),
                    ('decision_made', 'Решение принято'),
                    ('approved', 'Одобрено'),
                    ('rejected', 'Отклонено'),
                    ('continue', 'Продолжить'),
                ],
                default='planned',
                help_text='Статус заявки для конкретной области',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='applicationoblaststatus',
            name='trial_plan',
            field=models.ForeignKey(
                blank=True,
                help_text='Связанный план испытаний',
                null=True,
                on_delete=models.SET_NULL,
                related_name='application_oblast_statuses',
                to='trials_app.trialplan'
            ),
        ),
        migrations.AddField(
            model_name='applicationoblaststatus',
            name='trial',
            field=models.ForeignKey(
                blank=True,
                help_text='Связанное испытание',
                null=True,
                on_delete=models.SET_NULL,
                related_name='application_oblast_statuses',
                to='trials_app.trial'
            ),
        ),
        migrations.AddField(
            model_name='applicationoblaststatus',
            name='annual_decision_item',
            field=models.ForeignKey(
                blank=True,
                help_text='Связанное решение в годовой таблице',
                null=True,
                on_delete=models.SET_NULL,
                related_name='application_oblast_statuses',
                to='trials_app.annualdecisionitem'
            ),
        ),
        migrations.AddField(
            model_name='applicationoblaststatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationoblaststatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
