# Generated by Django 3.2.25 on 2025-10-18 14:09

from django.db import migrations, models


def add_fields_if_not_exist(apps, schema_editor):
    """Add fields only if they don't already exist"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if status column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='trials_app_applicationoblaststatus' 
            AND column_name='status'
        """)
        
        # If status column doesn't exist, the table wasn't created by migration 0019
        # In that case, we shouldn't be here - migration 0019 should have created all fields
        # This migration is essentially a no-op since migration 0019 creates all these fields


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0019_create_application_oblast_status'),
    ]

    operations = [
        # All fields (status, trial_plan, trial, annual_decision_item, created_at, updated_at)
        # are already created in migration 0019 when the ApplicationOblastStatus model is created.
        # This migration was generated in error and should not add duplicate fields.
        migrations.RunPython(add_fields_if_not_exist, migrations.RunPython.noop),
    ]
