# Generated by Django 3.2.25 on 2025-10-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0020_add_status_column'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE trials_app_application_target_oblasts ADD COLUMN status VARCHAR(20) DEFAULT 'planned';",
            "ALTER TABLE trials_app_application_target_oblasts DROP COLUMN status;"
        ),
        migrations.RunSQL(
            "ALTER TABLE trials_app_application_target_oblasts ADD COLUMN trial_plan_id INTEGER REFERENCES trials_app_trialplan(id) ON DELETE SET NULL;",
            "ALTER TABLE trials_app_application_target_oblasts DROP COLUMN trial_plan_id;"
        ),
        migrations.RunSQL(
            "ALTER TABLE trials_app_application_target_oblasts ADD COLUMN trial_id INTEGER REFERENCES trials_app_trial(id) ON DELETE SET NULL;",
            "ALTER TABLE trials_app_application_target_oblasts DROP COLUMN trial_id;"
        ),
        migrations.RunSQL(
            "ALTER TABLE trials_app_application_target_oblasts ADD COLUMN annual_decision_item_id INTEGER REFERENCES trials_app_annualdecisionitem(id) ON DELETE SET NULL;",
            "ALTER TABLE trials_app_application_target_oblasts DROP COLUMN annual_decision_item_id;"
        ),
        migrations.RunSQL(
            "ALTER TABLE trials_app_application_target_oblasts ADD COLUMN created_at TIMESTAMP DEFAULT NOW();",
            "ALTER TABLE trials_app_application_target_oblasts DROP COLUMN created_at;"
        ),
        migrations.RunSQL(
            "ALTER TABLE trials_app_application_target_oblasts ADD COLUMN updated_at TIMESTAMP DEFAULT NOW();",
            "ALTER TABLE trials_app_application_target_oblasts DROP COLUMN updated_at;"
        ),
    ]
