# Generated by Django 3.2.25 on 2025-10-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0021_add_status_to_existing_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationOblastStatus',
        ),
    ]
