# Generated by Django 3.2.25 on 2025-10-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0022_remove_application_oblast_status'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE trials_app_application_target_oblasts ADD COLUMN decision_date DATE NULL;",
            "ALTER TABLE trials_app_application_target_oblasts DROP COLUMN decision_date;"
        ),
        migrations.RunSQL(
            "ALTER TABLE trials_app_application_target_oblasts ADD COLUMN decision_justification TEXT NULL;",
            "ALTER TABLE trials_app_application_target_oblasts DROP COLUMN decision_justification;"
        ),
        migrations.RunSQL(
            "ALTER TABLE trials_app_application_target_oblasts ADD COLUMN decided_by_id INTEGER REFERENCES auth_user(id) ON DELETE SET NULL;",
            "ALTER TABLE trials_app_application_target_oblasts DROP COLUMN decided_by_id;"
        ),
        migrations.RunSQL(
            "ALTER TABLE trials_app_application_target_oblasts ADD COLUMN decision_year INTEGER NULL;",
            "ALTER TABLE trials_app_application_target_oblasts DROP COLUMN decision_year;"
        ),
    ]
