# Generated by Django 3.2.25 on 2025-10-18 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trials_app', '0023_add_decision_fields_to_target_oblasts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDecisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Год решения (например: 2024)')),
                ('decision', models.CharField(choices=[('continue', 'Продолжить испытания'), ('approved', 'Одобрено к включению в Госреестр'), ('rejected', 'Снять с испытаний')], help_text='Решение по сорту за год', max_length=20)),
                ('decision_date', models.DateField(help_text='Дата принятия решения')),
                ('decision_justification', models.TextField(blank=True, help_text='Обоснование принятого решения', null=True)),
                ('average_yield', models.FloatField(blank=True, help_text='Средняя урожайность за год (ц/га)', null=True)),
                ('years_tested_total', models.IntegerField(default=1, help_text='Общее количество лет испытаний на момент решения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(help_text='Заявка', on_delete=django.db.models.deletion.CASCADE, related_name='decision_history', to='trials_app.application')),
                ('decided_by', models.ForeignKey(blank=True, help_text='Кто принял решение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_made', to=settings.AUTH_USER_MODEL)),
                ('oblast', models.ForeignKey(help_text='Область', on_delete=django.db.models.deletion.CASCADE, related_name='application_decision_history', to='trials_app.oblast')),
            ],
            options={
                'verbose_name': 'История решения',
                'verbose_name_plural': 'История решений',
                'ordering': ['-year', '-decision_date'],
            },
        ),
        migrations.AddIndex(
            model_name='applicationdecisionhistory',
            index=models.Index(fields=['application', 'oblast', 'year'], name='trials_app__applica_df5144_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationdecisionhistory',
            index=models.Index(fields=['decision', 'year'], name='trials_app__decisio_646cbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationdecisionhistory',
            unique_together={('application', 'oblast', 'year')},
        ),
    ]
