# Generated by Django 3.2.25 on 2025-10-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0024_create_application_decision_history'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS trials_app_annualdecisionitem CASCADE;",
            migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS trials_app_annualdecisiontable CASCADE;",
            migrations.RunSQL.noop
        ),
    ]
