# Generated by Django 3.2.25 on 2025-10-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0025_remove_annual_decision_tables'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE trials_app_application_target_oblasts DROP COLUMN IF EXISTS annual_decision_item_id;",
            migrations.RunSQL.noop
        ),
    ]
