# Generated by Django 3.2.25 on 2025-10-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0026_remove_annual_decision_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='originator',
            name='code',
            field=models.IntegerField(blank=True, help_text='Код оригинатора', null=True),
        ),
        migrations.AddField(
            model_name='originator',
            name='is_foreign',
            field=models.BooleanField(default=False, help_text='Иностранный оригинатор'),
        ),
        migrations.AddField(
            model_name='originator',
            name='is_nanoc',
            field=models.BooleanField(default=False, help_text='НАНОЦ оригинатор'),
        ),
    ]
