# Generated by Django 3.2.25 on 2025-10-24 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trials_app', '0027_add_originator_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Код категории (A01, A02, A17 и т.д.)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Название категории', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория реестра',
                'verbose_name_plural': 'Категории реестра',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RegisterDiseaseResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Код устойчивости (I01, I02, I03 и т.д.)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Название устойчивости к болезням', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание устойчивости')),
            ],
            options={
                'verbose_name': 'Устойчивость к болезням',
                'verbose_name_plural': 'Устойчивость к болезням',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Код формы (G01, G02, G32 и т.д.)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Название формы', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание формы')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RegisterGrowingCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Код условия (F01, F14, F19 и т.д.)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Название условия выращивания', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание условия')),
            ],
            options={
                'verbose_name': 'Условие выращивания',
                'verbose_name_plural': 'Условия выращивания',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RegisterPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Код периода (C01, C02, C12 и т.д.)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Название периода потребления', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание периода')),
            ],
            options={
                'verbose_name': 'Период потребления',
                'verbose_name_plural': 'Периоды потребления',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RegisterPestResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Код устойчивости (H01, H02, H03 и т.д.)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Название устойчивости к вредителям', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание устойчивости')),
            ],
            options={
                'verbose_name': 'Устойчивость к вредителям',
                'verbose_name_plural': 'Устойчивость к вредителям',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RegisterPlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Код типа (E01, E02, E61 и т.д.)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Название типа растения', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание типа')),
            ],
            options={
                'verbose_name': 'Тип растения',
                'verbose_name_plural': 'Типы растений',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RegisterUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Код направления (B01, B02, B80 и т.д.)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Название направления использования', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание направления')),
            ],
            options={
                'verbose_name': 'Направление использования',
                'verbose_name_plural': 'Направления использования',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SortRegisterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_in_register', models.BooleanField(default=False, help_text='Включен ли сорт в реестр')),
                ('register_date', models.DateField(blank=True, help_text='Дата включения в реестр', null=True)),
                ('register_number', models.CharField(blank=True, help_text='Номер в реестре', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Дополнительные примечания по реестру')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Категория сорта (A-код)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trials_app.registercategory')),
                ('consumption_periods', models.ManyToManyField(blank=True, help_text='Периоды потребления (C-коды)', to='trials_app.RegisterPeriod')),
                ('created_by', models.ForeignKey(help_text='Кто создал запись реестра', on_delete=django.db.models.deletion.CASCADE, related_name='register_data_created', to=settings.AUTH_USER_MODEL)),
                ('disease_resistance', models.ManyToManyField(blank=True, help_text='Устойчивость к болезням (I-коды)', to='trials_app.RegisterDiseaseResistance')),
                ('forms', models.ManyToManyField(blank=True, help_text='Формы (G-коды)', to='trials_app.RegisterForm')),
                ('growing_conditions', models.ManyToManyField(blank=True, help_text='Условия выращивания (F-коды)', to='trials_app.RegisterGrowingCondition')),
                ('pest_resistance', models.ManyToManyField(blank=True, help_text='Устойчивость к вредителям (H-коды)', to='trials_app.RegisterPestResistance')),
                ('plant_types', models.ManyToManyField(blank=True, help_text='Типы растения (E-коды)', to='trials_app.RegisterPlantType')),
                ('sort_record', models.OneToOneField(help_text='Сорт, для которого хранятся данные реестра', on_delete=django.db.models.deletion.CASCADE, related_name='register_data', to='trials_app.sortrecord')),
                ('usage_directions', models.ManyToManyField(blank=True, help_text='Направления использования (B-коды)', to='trials_app.RegisterUsage')),
            ],
            options={
                'verbose_name': 'Данные реестра сорта',
                'verbose_name_plural': 'Данные реестра сортов',
                'ordering': ['-created_at'],
            },
        ),
    ]
