# Generated by Django 3.2.25 on 2025-11-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0029_sortoblast'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupculture',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='Регионы (ГСУ), в которых испытывается данная группа культур', related_name='group_cultures', to='trials_app.Region'),
        ),
    ]
