# Generated by Django 3.2.25 on 2026-03-18 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_application_oblast_states(apps, schema_editor):
    ApplicationOblastState = apps.get_model('trials_app', 'ApplicationOblastState')

    try:
        with schema_editor.connection.cursor() as cursor:
            try:
                cursor.execute(
                    """
                    SELECT
                        application_id,
                        oblast_id,
                        COALESCE(status, 'planned'),
                        trial_plan_id,
                        trial_id,
                        decision_date,
                        decision_justification,
                        decided_by_id,
                        decision_year
                    FROM trials_app_application_target_oblasts
                    """
                )
                rows = cursor.fetchall()
            except Exception:
                cursor.execute(
                    """
                    SELECT
                        application_id,
                        oblast_id
                    FROM trials_app_application_target_oblasts
                    """
                )
                rows = [
                    (application_id, oblast_id, 'planned', None, None, None, None, None, None)
                    for application_id, oblast_id in cursor.fetchall()
                ]
    except Exception:
        return

    for (
        application_id,
        oblast_id,
        status,
        trial_plan_id,
        trial_id,
        decision_date,
        decision_justification,
        decided_by_id,
        decision_year,
    ) in rows:
        ApplicationOblastState.objects.update_or_create(
            application_id=application_id,
            oblast_id=oblast_id,
            is_deleted=False,
            defaults={
                'status': status or 'planned',
                'trial_plan_id': trial_plan_id,
                'trial_id': trial_id,
                'decision_date': decision_date,
                'decision_justification': decision_justification,
                'decided_by_id': decided_by_id,
                'decision_year': decision_year,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trials_app', '0030_groupculture_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='decided_by',
            field=models.ForeignKey(blank=True, help_text='Кто принял решение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_trials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trial',
            name='decision',
            field=models.CharField(blank=True, choices=[('approved', 'Одобрено'), ('continue', 'Продолжить'), ('rejected', 'Отклонено')], help_text='Решение комиссии по испытанию', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='decision_date',
            field=models.DateField(blank=True, help_text='Дата принятия решения', null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='decision_justification',
            field=models.TextField(blank=True, help_text='Обоснование решения', null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='decision_recommendations',
            field=models.TextField(blank=True, help_text='Рекомендации комиссии', null=True),
        ),
        migrations.CreateModel(
            name='ApplicationOblastState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('trial_plan_created', 'План создан'), ('trial_created', 'Испытание создано'), ('trial_in_progress', 'Испытание идет'), ('trial_completed', 'Испытание завершено'), ('decision_pending', 'Ожидает решения'), ('decision_made', 'Решение принято'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('continue', 'Продолжить')], default='planned', help_text='Статус заявки для конкретной области', max_length=20)),
                ('decision_date', models.DateField(blank=True, help_text='Дата решения', null=True)),
                ('decision_justification', models.TextField(blank=True, help_text='Обоснование решения', null=True)),
                ('decision_year', models.IntegerField(blank=True, help_text='Год решения', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(help_text='Заявка', on_delete=django.db.models.deletion.CASCADE, related_name='oblast_states', to='trials_app.application')),
                ('decided_by', models.ForeignKey(blank=True, help_text='Кто принял решение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_oblast_state_decisions', to=settings.AUTH_USER_MODEL)),
                ('oblast', models.ForeignKey(help_text='Область', on_delete=django.db.models.deletion.CASCADE, related_name='application_states', to='trials_app.oblast')),
                ('trial', models.ForeignKey(blank=True, help_text='Связанное испытание', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_oblast_states', to='trials_app.trial')),
                ('trial_plan', models.ForeignKey(blank=True, help_text='Связанный план испытаний', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_oblast_states', to='trials_app.trialplan')),
            ],
            options={
                'verbose_name': 'Состояние заявки по области',
                'verbose_name_plural': 'Состояния заявок по областям',
                'ordering': ['application', 'oblast__name'],
            },
        ),
        migrations.AddIndex(
            model_name='applicationoblaststate',
            index=models.Index(fields=['application', 'oblast', 'is_deleted'], name='trials_app__applica_1809c4_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationoblaststate',
            index=models.Index(fields=['status', 'is_deleted'], name='trials_app__status_53a985_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationoblaststate',
            unique_together={('application', 'oblast', 'is_deleted')},
        ),
        migrations.RunPython(backfill_application_oblast_states, migrations.RunPython.noop),
    ]
