# Generated by Django 3.2.25 on 2026-03-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0031_workflow_core_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationoblaststate',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('trial_plan_created', 'План создан'), ('trial_created', 'Испытание создано'), ('trial_in_progress', 'Испытание идет'), ('trial_completed', 'Испытание завершено'), ('decision_pending', 'Ожидает решения'), ('decision_made', 'Решение принято'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('continue', 'Продолжить'), ('removed', 'Исключён из реестра'), ('withdrawn', 'Отозван заявителем')], default='planned', help_text='Статус заявки для конкретной области', max_length=20),
        ),
    ]
