# Generated by Django 3.2.25 on 2026-03-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials_app', '0032_add_removed_withdrawn_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='is_winter',
            field=models.BooleanField(default=False, verbose_name='Озимая культура'),
        ),
    ]
