# Generated by Django 5.2.12 on 2026-04-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trials_app", "0034_add_country_to_originator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("submitted", "Подана"),
                    ("distributed", "Распределена по областям"),
                    ("in_progress", "Испытания проводятся"),
                    ("completed", "Испытания завершены"),
                    ("registered", "Включен в реестр"),
                    ("rejected", "Снята с испытаний"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationdecisionhistory",
            name="decision",
            field=models.CharField(
                choices=[
                    ("continue", "Продолжить испытания"),
                    ("approved", "Одобрено к включению в Госреестр"),
                    ("rejected", "Снять с испытаний"),
                    ("removed", "Снят из Госреестра"),
                    ("withdrawn", "Отозван заявителем"),
                ],
                help_text="Решение по сорту за год",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationoblaststate",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Запланировано"),
                    ("trial_plan_created", "План создан"),
                    ("trial_created", "Испытание создано"),
                    ("trial_in_progress", "Испытание идет"),
                    ("trial_completed", "Испытание завершено"),
                    ("decision_pending", "Ожидает решения"),
                    ("decision_made", "Решение принято"),
                    ("approved", "Допуск"),
                    ("rejected", "Снят с испытаний"),
                    ("continue", "Продолжить"),
                    ("removed", "Снят"),
                    ("withdrawn", "Отозван"),
                ],
                default="planned",
                help_text="Статус заявки для конкретной области",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="planneddistribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Запланировано"),
                    ("in_progress", "Испытания идут"),
                    ("approved", "Допуск"),
                    ("rejected", "Снят с испытаний"),
                    ("cancelled", "Отменено"),
                ],
                default="planned",
                help_text="Статус распределения",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trial",
            name="decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approved", "Допуск"),
                    ("continue", "Продолжить"),
                    ("rejected", "Снят с испытаний"),
                ],
                help_text="Решение комиссии по испытанию",
                max_length=20,
                null=True,
            ),
        ),
    ]
